# Generated by Django 3.2.12 on 2022-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=models.CharField(default='doctor', max_length=10),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='type',
            field=models.CharField(default='Receptionist', max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='Password',
            field=models.CharField(max_length=32),
        ),
    ]
