# Generated by Django 3.2.12 on 2022-04-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220322_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_ID',
            new_name='Add',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='BloodGroup',
            new_name='BG',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Address',
            new_name='PID',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Phone',
            new_name='PN',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Gender',
            new_name='gender',
        ),
    ]
